### ISSUE TITLE
`allowedValues` appears to only allow values prefixed with @ symbol

### ISSUE THREAD

**Issue by brandonb927** [scottmcginness/eslint-plugin-tags-validator#2]
As the title says, it looks like tags are [required to be prefixed](https://github.com/scottmcginness/eslint-plugin-tags-validator/blob/master/lib/constants.js#L25) with `@` symbol, when there is no requirement for this using the `@cypress/grep` or `@bahmutov/cy-grep` plugin. Can this be made configurable? We use tags without that symbol because it's easier for us.

**Comment by scottmcginness** [comment]
Very good point!
I have [a change in a branch](https://github.com/scottmcginness/eslint-plugin-tags-validator/tree/loosen-at-sign) that fixes this with a configuration setting called `prependAtSign`, which would default to `true`, but setting it to `false` explicitly keeps the tags "as defined" in the rule.

I'm not sold on the name or the default yet, but it should work. Feel free to check it out if you like while I test that it does what I think it does :D.

If you're interested, it was like this because:
  - It was recommended, and looks good to me in the test files, but I didn't want to repeat the `@` sign in the rule
  - I started out with just the `markdownFile` option, which required _some_ prefix (and still does)

**Comment by brandonb927** [comment]
@scottmcginness I've been testing out your branch and it's working great! I've been able to implement a minimum level of tag enforcement with this branch in a branch of my own so I would say this is ready to be merged as-is.

**Comment by scottmcginness** [comment]
Great, thank you for taking the time to try it out.
I'm going to merge this now, and it will be up in version `1.4.0` shortly.
